In [1]:
import pandas as pd
import numpy as np

In [17]:
df=pd.read_csv(r"C:\Users\batch1\Downloads\logs_dataset (1).csv")
df.head()

                    @timestamp                   _id  ip_address
0  July 8th 2019, 14:43:03.000  XswJ0msBoTGddM7vxMDB  10.1.1.285
1  July 8th 2019, 14:43:01.000  dKQJ0msB7mP0GwVzvJjz  10.1.2.389
2  July 8th 2019, 14:42:59.000  CcwJ0msBoTGddM7vtb8y  10.1.1.415
3  July 8th 2019, 14:42:57.000  bKQJ0msB7mP0GwVzrZdT   10.1.1.79
4  July 8th 2019, 14:42:55.000  L6QJ0msB7mP0GwVzpZeI   10.1.1.60

In [18]:
len(df)

721547

In [19]:
df['@timestamp'] = (        
    df['@timestamp']                  
    .str.replace(r'(\d+)(st|nd|rd|th)', r'\1', regex=True)                  
)                  
df['@timestamp'] = pd.to_datetime(                                      
    df['@timestamp'],                                      
    format='%B %d %Y, %H:%M:%S.%f' 
)

In [20]:
df.head()

           @timestamp                   _id  ip_address
0 2019-07-08 14:43:03  XswJ0msBoTGddM7vxMDB  10.1.1.285
1 2019-07-08 14:43:01  dKQJ0msB7mP0GwVzvJjz  10.1.2.389
2 2019-07-08 14:42:59  CcwJ0msBoTGddM7vtb8y  10.1.1.415
3 2019-07-08 14:42:57  bKQJ0msB7mP0GwVzrZdT   10.1.1.79
4 2019-07-08 14:42:55  L6QJ0msB7mP0GwVzpZeI   10.1.1.60

In [21]:
df['shift_time']=df.groupby(['ip_address'])['@timestamp'].shift(1)

In [22]:
df.head()

           @timestamp                   _id  ip_address shift_time
0 2019-07-08 14:43:03  XswJ0msBoTGddM7vxMDB  10.1.1.285        NaT
1 2019-07-08 14:43:01  dKQJ0msB7mP0GwVzvJjz  10.1.2.389        NaT
2 2019-07-08 14:42:59  CcwJ0msBoTGddM7vtb8y  10.1.1.415        NaT
3 2019-07-08 14:42:57  bKQJ0msB7mP0GwVzrZdT   10.1.1.79        NaT
4 2019-07-08 14:42:55  L6QJ0msB7mP0GwVzpZeI   10.1.1.60        NaT

In [23]:
df['time_diff'] = (df['@timestamp']-df['shift_time']).dt.seconds//60
df.head()

           @timestamp                   _id  ip_address shift_time  time_diff
0 2019-07-08 14:43:03  XswJ0msBoTGddM7vxMDB  10.1.1.285        NaT        NaN
1 2019-07-08 14:43:01  dKQJ0msB7mP0GwVzvJjz  10.1.2.389        NaT        NaN
2 2019-07-08 14:42:59  CcwJ0msBoTGddM7vtb8y  10.1.1.415        NaT        NaN
3 2019-07-08 14:42:57  bKQJ0msB7mP0GwVzrZdT   10.1.1.79        NaT        NaN
4 2019-07-08 14:42:55  L6QJ0msB7mP0GwVzpZeI   10.1.1.60        NaT        NaN

In [24]:
df['date'] = df['@timestamp'].dt.date
df.head()

,@timestamp,_id,ip_address,shift_time,time_diff,date
0,2019-07-08 14:43:03,XswJ0msBoTGddM7vxMDB,10.1.1.285,NaT,NaN,2019-07-08
1,2019-07-08 14:43:01,dKQJ0msB7mP0GwVzvJjz,10.1.2.389,NaT,NaN,2019-07-08
2,2019-07-08 14:42:59,CcwJ0msBoTGddM7vtb8y,10.1.1.415,NaT,NaN,2019-07-08
3,2019-07-08 14:42:57,bKQJ0msB7mP0GwVzrZdT,10.1.1.79,NaT,NaN,2019-07-08
4,2019-07-08 14:42:55,L6QJ0msB7mP0GwVzpZeI,10.1.1.60,NaT,NaN,2019-07-08

In [25]:
df['weekday'] = df['@timestamp'].dt.weekday
df.head()

,@timestamp,_id,ip_address,shift_time,time_diff,date,weekday
0,2019-07-08 14:43:03,XswJ0msBoTGddM7vxMDB,10.1.1.285,NaT,NaN,2019-07-08,0
1,2019-07-08 14:43:01,dKQJ0msB7mP0GwVzvJjz,10.1.2.389,NaT,NaN,2019-07-08,0
2,2019-07-08 14:42:59,CcwJ0msBoTGddM7vtb8y,10.1.1.415,NaT,NaN,2019-07-08,0
3,2019-07-08 14:42:57,bKQJ0msB7mP0GwVzrZdT,10.1.1.79,NaT,NaN,2019-07-08,0
4,2019-07-08 14:42:55,L6QJ0msB7mP0GwVzpZeI,10.1.1.60,NaT,NaN,2019-07-08,0

In [26]:
df['hour'] = df['@timestamp'].dt.hour
df.head()

,@timestamp,_id,ip_address,shift_time,time_diff,date,weekday,hour
0,2019-07-08 14:43:03,XswJ0msBoTGddM7vxMDB,10.1.1.285,NaT,NaN,2019-07-08,0,14
1,2019-07-08 14:43:01,dKQJ0msB7mP0GwVzvJjz,10.1.2.389,NaT,NaN,2019-07-08,0,14
2,2019-07-08 14:42:59,CcwJ0msBoTGddM7vtb8y,10.1.1.415,NaT,NaN,2019-07-08,0,14
3,2019-07-08 14:42:57,bKQJ0msB7mP0GwVzrZdT,10.1.1.79,NaT,NaN,2019-07-08,0,14
4,2019-07-08 14:42:55,L6QJ0msB7mP0GwVzpZeI,10.1.1.60,NaT,NaN,2019-07-08,0,14

In [27]:
df['is_weekend'] = ((df['weekday'] == 5) | (df['weekday'] == 6)).astype(int)
df.head()

,@timestamp,_id,ip_address,shift_time,time_diff,date,weekday,hour,is_weekend
0,2019-07-08 14:43:03,XswJ0msBoTGddM7vxMDB,10.1.1.285,NaT,NaN,2019-07-08,0,14,0
1,2019-07-08 14:43:01,dKQJ0msB7mP0GwVzvJjz,10.1.2.389,NaT,NaN,2019-07-08,0,14,0
2,2019-07-08 14:42:59,CcwJ0msBoTGddM7vtb8y,10.1.1.415,NaT,NaN,2019-07-08,0,14,0
3,2019-07-08 14:42:57,bKQJ0msB7mP0GwVzrZdT,10.1.1.79,NaT,NaN,2019-07-08,0,14,0
4,2019-07-08 14:42:55,L6QJ0msB7mP0GwVzpZeI,10.1.1.60,NaT,NaN,2019-07-08,0,14,0

In [28]:
df['hour_bucket'] = df['hour']//4
df.head()

,@timestamp,_id,ip_address,shift_time,time_diff,date,weekday,hour,is_weekend,hour_bucket
0,2019-07-08 14:43:03,XswJ0msBoTGddM7vxMDB,10.1.1.285,NaT,NaN,2019-07-08,0,14,0,3
1,2019-07-08 14:43:01,dKQJ0msB7mP0GwVzvJjz,10.1.2.389,NaT,NaN,2019-07-08,0,14,0,3
2,2019-07-08 14:42:59,CcwJ0msBoTGddM7vtb8y,10.1.1.415,NaT,NaN,2019-07-08,0,14,0,3
3,2019-07-08 14:42:57,bKQJ0msB7mP0GwVzrZdT,10.1.1.79,NaT,NaN,2019-07-08,0,14,0,3
4,2019-07-08 14:42:55,L6QJ0msB7mP0GwVzpZeI,10.1.1.60,NaT,NaN,2019-07-08,0,14,0,3

In [29]:
ip_addr ='ip_address'
#This line counts the number of events per IP and stores it in a DataFrame.
#[Counting how many times the user in logging into the computer wrt to ip address]
ip_counts = df.groupby(ip_addr)['@timestamp'].count().reset_index()
ip_counts.head()

   ip_address  @timestamp
0    10.1.1.1        1446
1  10.1.1.100        2860
2  10.1.1.101        1465
3  10.1.1.106        1408
4  10.1.1.109        1459

In [30]:
ip_counts = ip_counts.rename(columns={'@timestamp':'total_count'})

In [31]:
daily_counts = df.groupby([ip_addr,'date'])['@timestamp'].count().reset_index()

In [32]:
daily_counts = daily_counts.rename(columns={'@timestamp':'daily_counts'})

In [33]:
daily_counts_avg = daily_counts.groupby(ip_addr).daily_counts.median().reset_index()

In [34]:
daily_counts_avg.head(5)

   ip_address  daily_counts
0    10.1.1.1          40.0
1  10.1.1.100          78.0
2  10.1.1.101          40.0
3  10.1.1.106          35.5
4  10.1.1.109          42.5

In [35]:
weekend_counts = df.groupby([ip_addr, 'is_weekend'])['@timestamp'].count().reset_index()

In [36]:
weekend_counts

     ip_address  is_weekend  @timestamp
0      10.1.1.1           0         975
1      10.1.1.1           1         471
2    10.1.1.100           0        1960
3    10.1.1.100           1         900
4    10.1.1.101           0        1006
..          ...         ...         ...
767   10.1.2.90           1         871
768   10.1.2.95           0        1973
769   10.1.2.95           1         895
770   10.1.2.99           0         978
771   10.1.2.99           1         445

[772 rows x 3 columns]